## 22기 교육세션 [통계기초, 회귀분석] 과제

### 선형 회귀분석에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.

#### 데이터 불러오기

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import pandas as pd 
data = pd.read_csv("/content/gdrive/MyDrive/Colab/assignment.csv")

In [3]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [4]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [5]:
X = data.drop(["y"], axis=1)
y = data.y

In [6]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [7]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [40]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

#### 정규방정식

In [10]:
import numpy as np
from numpy.linalg import inv 

In [15]:
designX = np.concatenate((np.ones((9,1), dtype=int), X), axis=1)
designX

array([[ 1.000e+00,  3.890e+01,  6.470e+01,  4.000e+00,  8.680e+02,
         5.970e+01],
       [ 1.000e+00,  4.160e+01,  4.530e+01, -4.000e+00,  9.570e+02,
         6.140e+01],
       [ 1.000e+00,  3.970e+01,  7.410e+01,  8.000e+00,  7.860e+02,
         6.100e+01],
       [ 1.000e+00,  3.730e+01,  4.800e+01,  1.900e+01,  9.840e+02,
         6.750e+01],
       [ 1.000e+00,  3.950e+01,  5.190e+01,  6.000e+00,  7.000e+02,
         5.720e+01],
       [ 1.000e+00,  3.740e+01,  5.360e+01, -5.000e+00,  1.037e+03,
         5.880e+01],
       [ 1.000e+00,  3.510e+01,  7.140e+01,  3.000e+00,  9.860e+02,
         5.860e+01],
       [ 1.000e+00,  3.880e+01,  5.830e+01,  6.000e+00,  8.190e+02,
         5.920e+01],
       [ 1.000e+00,  3.660e+01,  5.260e+01, -1.900e+01,  7.910e+02,
         5.440e+01]])

In [25]:
gradX = np.gradient(designX, axis = 1)
gradX

array([[  37.9 ,   31.85,  -17.45,  401.65,   27.85, -808.3 ],
       [  40.6 ,   22.15,  -22.8 ,  455.85,   32.7 , -895.6 ],
       [  38.7 ,   36.55,  -15.85,  355.95,   26.5 , -725.  ],
       [  36.3 ,   23.5 ,   -9.15,  468.  ,   24.25, -916.5 ],
       [  38.5 ,   25.45,  -16.75,  324.05,   25.6 , -642.8 ],
       [  36.4 ,   26.3 ,  -21.2 ,  491.7 ,   31.9 , -978.2 ],
       [  34.1 ,   35.2 ,  -16.05,  457.3 ,   27.8 , -927.4 ],
       [  37.8 ,   28.65,  -16.4 ,  380.35,   26.6 , -759.8 ],
       [  35.6 ,   25.8 ,  -27.8 ,  369.2 ,   36.7 , -736.6 ]])

In [35]:
invX = designX*gradX
invX

array([[ 3.790000e+01,  1.238965e+03, -1.129015e+03,  1.606600e+03,
         2.417380e+04, -4.825551e+04],
       [ 4.060000e+01,  9.214400e+02, -1.032840e+03, -1.823400e+03,
         3.129390e+04, -5.498984e+04],
       [ 3.870000e+01,  1.451035e+03, -1.174485e+03,  2.847600e+03,
         2.082900e+04, -4.422500e+04],
       [ 3.630000e+01,  8.765500e+02, -4.392000e+02,  8.892000e+03,
         2.386200e+04, -6.186375e+04],
       [ 3.850000e+01,  1.005275e+03, -8.693250e+02,  1.944300e+03,
         1.792000e+04, -3.676816e+04],
       [ 3.640000e+01,  9.836200e+02, -1.136320e+03, -2.458500e+03,
         3.308030e+04, -5.751816e+04],
       [ 3.410000e+01,  1.235520e+03, -1.145970e+03,  1.371900e+03,
         2.741080e+04, -5.434564e+04],
       [ 3.780000e+01,  1.111620e+03, -9.561200e+02,  2.282100e+03,
         2.178540e+04, -4.498016e+04],
       [ 3.560000e+01,  9.442800e+02, -1.462280e+03, -7.014800e+03,
         2.902970e+04, -4.007104e+04]])

In [39]:
mul2 = np.matmul(y,designX)
mul2

array([   80. ,  3090.9,  4643.8,   192. , 70731. ,  4794.5])

In [38]:
result = mul2 / invX
result

array([[  2.11081794,   2.4947436 ,  -4.11314287,   0.11950703,
          2.92593634,  -0.09935653],
       [  1.97044335,   3.35442351,  -4.49614655,  -0.1052978 ,
          2.26021685,  -0.08718883],
       [  2.06718346,   2.1301347 ,  -3.9539032 ,   0.0674252 ,
          3.39579433,  -0.10841153],
       [  2.20385675,   3.52621071, -10.57331512,   0.02159244,
          2.96416897,  -0.07750096],
       [  2.07792208,   3.07468106,  -5.34184568,   0.09875019,
          3.94704241,  -0.13039815],
       [  2.1978022 ,   3.14237205,  -4.08670093,  -0.0780964 ,
          2.13816078,  -0.08335628],
       [  2.34604106,   2.50169969,  -4.05228758,   0.13995189,
          2.58040626,  -0.08822235],
       [  2.11640212,   2.78053651,  -4.85692173,   0.08413304,
          3.24671569,  -0.10659144],
       [  2.24719101,   3.27328758,  -3.17572558,  -0.0273707 ,
          2.43650468,  -0.11965   ]])

In [41]:
gradX = np.gradient(designX, axis = 1)

b_hat = np.linalg.inv(designX*gradX) * (gradX * y)
b_hat

LinAlgError: ignored

In [ ]:
# designX는 다중선형회귀를 가정하였을 때의 설명변수 행렬 (design matrix)로, 
# 강의 자료 기준으로는 다중선형회귀 LSE 행렬 표현의 'X' 행렬을 의미합니다.
# statsmodel package나 numpy package로 어렵지 않게 구현 가능합니다.

def estimate_beta(X, y):
    designX =   # 세션자료 Unit 02, 다중선형회귀분석 LSE 파트 참고해주세요 :)
    beta_hat = 
    
    return beta_hat

In [ ]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [27]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135655
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]
